{{ if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: misskey-backup
spec:
  schedule: {{ .Values.backup.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: swissknife
            image: ghcr.io/totegamma/swissknife:master
            env:
            - name: PGPASSWORD
              value: {{ .Values.db.password | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.backup.aws_access_key_id | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.backup.aws_secret_access_key | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.backup.aws_default_region | quote }}
            command:
            - /bin/sh
            - -cex
            - pg_dump -Fc -d {{ .Values.db.name }} -h {{ .Values.db.hostname }} -U {{ .Values.db.username }} > misskey.dump
            - zip misskey.dump misskey.dump.zip
            - zip -r files.dump files/
            - aws s3 sync . {{ .Values.backup.s3key }} --include "*.zip"
            volumeMounts:
              - name: misskey-files
                mountPath: /workdir/files
          volumes:
            - name: misskey-files
              persistentVolumeClaim:
                claimName: misskey-files
{{ end }}
