apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.web.fileStorageSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-varlib
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.fileStorageSize }}

