apiVersion: v1
kind: Service
metadata:
  name: misskey
  labels:
    name: misskey
spec:
  ports:
  - port: {{ .Values.web.port }}
    protocol: TCP
  selector:
    name: misskey-web
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.hostname }}
  labels:
    name: misskey-db
spec:
  ports:
  - port: {{ .Values.db.port }}
    protocol: TCP
  selector:
    name: misskey-db
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.hostname }}
  labels:
    name: misskey-redis
spec:
  ports:
  - port: {{ .Values.redis.port }}
    protocol: TCP
  selector:
    name: misskey-redis
  type: ClusterIP

