apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: misskey-db
spec:
  postgresVersion: {{ .Values.db.postgresVersion }}
  port: {{ .Values.db.port }}
  users:
    - name: {{ .Values.db.username }}
      password: {{ .Values.db.password }}
  instances:
    - name: {{ .Values.db.hostname }}
      replicas: {{ .Values.db.replicas }}
      dataVolumeClaimSpec:
        storageClassName: {{ .Values.db.storageClassName }}
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storageSize }}
