apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: misskey-db
spec:
  postgresVersion: {{ .Values.db.postgresVersion }}
  port: {{ .Values.db.port }}
  users:
    - name: {{ .Values.db.username }}
      options: SUPERUSER
  instances:
    - name: {{ .Values.db.hostname }}
      replicas: {{ .Values.db.replicas }}
      dataVolumeClaimSpec:
        storageClassName: {{ .Values.db.storageClassName }}
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.db.storageSize }}
  backups:
    pgbackrest:
      repos:
        - name: repo1
          s3:
            bucket: {{ .Values.db.backup.bucket }}
            endpoint: {{ .Values.db.backup.endpoint }}
            region: {{ .Values.db.backup.region }}
          schedules:
            full: {{ .Values.db.backup.schedules.full }}
            differential: {{ .Values.db.backup.schedules.differential }}
      manual:
        repoName: repo1
        options:
          - --type=full
