apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  generation: 1
  labels:
    team: acid
  name: {{ .Values.db.hostname }}
spec:
  allowedSourceRanges: null
  numberOfInstances: {{ .Values.db.numberOfInstances }}
  postgresql:
    version: {{ .Values.db.postgresVersion }}
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    {{ .Values.db.username }}: []
  volume:
    size: {{ .Values.db.fileStorageSize }}

