apiVersion: v1
kind: Secret
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: {{ .Values.db.hostname }}
    postgres-operator.crunchydata.com/pguser: {{ .Values.db.username }}
    postgres-operator.crunchydata.com/role: pguser
  name: {{ .Values.db.hostname }}-pguser-{{ .Values.db.username }}
data:
  user: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
