apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrent-config
data:
  config.yaml: |-
    server:
      dsn: {{ .Values.server.dsn }}
      redisAddr: {{ .Values.server.redisAddr }}
      logPath: "/var/log/concurrent"
      traceEndpoint: "localhost:4318"
      enableTrace: true
      captchaSitekey: {{ .Values.server.captchaSitekey }}
      captchaSecret: {{ .Values.server.captchaSecret }}

    concurrent:
      fqdn: {{ .Values.concurrent.fqdn }}
      registration: {{ .Values.concurrent.registration }}
      ccid: {{ .Values.concurrent.ccid }}
      publickey: {{ .Values.concurrent.publickey }}
      privatekey: {{ .Values.concurrent.privatekey }}

    profile:
      nickname: {{ .Values.profile.nickname }}
      description: {{ .Values.profile.description }}
      logo: {{ .Values.profile.logo }}
      wordmark: {{ .Values.profile.wordmark }}
      themeColor: {{ .Values.profile.themeColor | quote }}
      rules: {{ .Values.profile.rules | toYaml | indent 6 }}
      tosURL: {{ .Values.profile.tosURL }}
      maintainerName: {{ .Values.profile.maintainerName }}
      maintainerEmail: {{ .Values.profile.maintainerEmail }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  gateway.yaml: |-
    services:
      - name: webui
        host: ccwebui
        port: 80
        path: /web
        preservePath: true
      - name: concurrent
        host: ccapi
        port: 8000
        path: /api/v1
        injectCors: true
      - name: activitypub
        host: ccactivitypub
        port: 8000
        path: /ap
        preservePath: true
      - name: webfinger
        host: ccactivitypub
        port: 8000
        path: /.well-known
        preservePath: true
{{- if (index .Values "url-summary" "enabled") }}
      - name: url-summary
        host: url-summary-lb
        port: {{ (index .Values "url-summary" "LB_LISTEN_PORT") }}
        path: /summary
{{- end }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: activitypub-config
data:
  activitypub.yaml: |-
    workerPrivateKey: {{ .Values.activitypub.privatekey }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  agent.yaml: |-
    server:
      log_level: debug

    metrics:
      configs:
        - name: default
          scrape_configs:
          - job_name: "concurrent"
            static_configs:
              - targets: ["concurrent:80"]
                labels:
                  instance: {{ .Values.concurrent.fqdn | quote }}
          remote_write:
            - url: {{ .Values.observability.metrics.endpoint }}
              basic_auth:
                username: {{ .Values.observability.metrics.username }}
                password: {{ .Values.observability.metrics.password }}

    logs:
      configs:
        - name: default
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: default
              static_configs:
                - targets: [localhost]
                  labels:
                    instance: {{ .Values.concurrent.fqdn | quote }}
                    job: applog
                    __path__: /var/log/concurrent/*.log
          clients:
            - url: {{ .Values.observability.logs.url }}

    traces:
      configs:
      - name: default
        receivers:
          otlp:
            protocols:
              http:
                endpoint: 0.0.0.0:4318
        remote_write:
          - endpoint: {{ .Values.observability.traces.endpoint }}
            basic_auth:
              username: {{ .Values.observability.traces.username }}
              password: {{ .Values.observability.traces.password }}
        batch:
          timeout: 5s
          send_batch_size: 100

