apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrent-config
data:
  config.yaml: |-
    server:
      dsn: {{ .Values.server.dsn }}
      redisAddr: {{ .Values.server.redisAddr }}

    concurrent:
      fqdn: {{ .Values.concurrent.fqdn }}
      ccaddr: {{ .Values.concurrent.ccaddr }}
      publickey: {{ .Values.concurrent.publickey }}
      privatekey: {{ .Values.concurrent.privatekey }}
      admins:
        - {{ .Values.concurrent.admin }}

    nodeinfo:
      openRegistrations: {{ .Values.nodeinfo.openRegistrations }}
      metadata:
        nodeName: {{ .Values.nodeinfo.nodeName }}
        nodeDescription: {{ .Values.nodeinfo.nodeDescription }}
        maintainer:
          name: {{ .Values.nodeinfo.maintainer.name }}
          email: {{ .Values.nodeinfo.maintainer.email }}
        themeColor: {{ .Values.nodeinfo.themeColor }}
