apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrent-config
data:
  config.yaml: |-
    server:
      dsn: {{ .Values.server.dsn }}
      redisAddr: {{ .Values.server.redisAddr }}
      logPath: "/var/log/concurrent"
      traceEndpoint: "localhost:4318"
      enableTrace: true

    concurrent:
      fqdn: {{ .Values.concurrent.fqdn }}
      registration: {{ .Values.concurrent.registration }}
      ccaddr: {{ .Values.concurrent.ccaddr }}
      publickey: {{ .Values.concurrent.publickey }}
      privatekey: {{ .Values.concurrent.privatekey }}
      admins:
        - {{ .Values.concurrent.admin }}

    profile:
      nickname: {{ .Values.profile.nickname }}
      description: {{ .Values.profile.description }}
      logo: {{ .Values.profile.logo }}
      wordmark: {{ .Values.profile.wordmark }}
      themeColor: {{ .Values.profile.themeColor | quote }}
      rules: {{ .Values.profile.rules | toYaml | indent 6 }}
      tosURL: {{ .Values.profile.tosURL }}
      maintainerName: {{ .Values.profile.maintainer.name }}
      maintainerEmail: {{ .Values.profile.maintainer.email }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  agent.yaml: |-
    server:
      log_level: debug

    metrics:
      configs:
        - name: default
          scrape_configs:
          - job_name: "concurrent"
            static_configs:
              - targets: ["concurrent:80"]
                labels:
                  instance: {{ .Values.concurrent.fqdn | quote }}
          remote_write:
            - url: {{ .Values.observability.metrics.endpoint }}
              basic_auth:
                username: {{ .Values.observability.metrics.username }}
                password: {{ .Values.observability.metrics.password }}

    logs:
      configs:
        - name: default
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: default
              static_configs:
                - targets: [localhost]
                  labels:
                    instance: {{ .Values.concurrent.fqdn | quote }}
                    job: accesslog
                    __path__: /var/log/concurrent/access.log
          clients:
            - url: {{ .Values.observability.logs.url }}

    traces:
      configs:
      - name: default
        receivers:
          otlp:
            protocols:
              http:
                endpoint: 0.0.0.0:4318
        remote_write:
          - endpoint: {{ .Values.observability.traces.endpoint }}
            basic_auth:
              username: {{ .Values.observability.traces.username }}
              password: {{ .Values.observability.traces.password }}
        batch:
          timeout: 5s
          send_batch_size: 100

