apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrent-config
data:
  config.yaml: |-
    server:
      dsn: {{ .Values.server.dsn }}
      redisAddr: {{ .Values.server.redisAddr }}
      logPath: "/var/log/concurrent"
      traceEndpoint: "localhost:4318"
      enableTrace: true

    concurrent:
      fqdn: {{ .Values.concurrent.fqdn }}
      ccaddr: {{ .Values.concurrent.ccaddr }}
      publickey: {{ .Values.concurrent.publickey }}
      privatekey: {{ .Values.concurrent.privatekey }}
      admins:
        - {{ .Values.concurrent.admin }}

    nodeinfo:
      openRegistrations: {{ .Values.nodeinfo.openRegistrations }}
      metadata:
        nodeName: {{ .Values.nodeinfo.nodeName }}
        nodeDescription: {{ .Values.nodeinfo.nodeDescription }}
        maintainer:
          name: {{ .Values.nodeinfo.maintainer.name }}
          email: {{ .Values.nodeinfo.maintainer.email }}
        themeColor: {{ .Values.nodeinfo.themeColor | quote }}

    profile:
      nickname: {{ .Values.profile.nickname }}
      description: {{ .Values.profile.description }}
      logo: {{ .Values.profile.logo }}
      wordmark: {{ .Values.profile.wordmark }}
      rules: {{ .Values.profile.rules | toYaml | nindent 3 }}
      tosURL: {{ .Values.profile.tosURL }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  agent.yaml: |-
    server:
      log_level: debug

    logs:
      configs:
        - name: default
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: default
              static_configs:
                - targets: [localhost]
                  labels:
                    job: accesslog
                    __path__: /var/log/concurrent/access.log
          clients:
            - url: {{ .Values.observability.logs.url }}

    traces:
      configs:
      - name: default
        receivers:
          otlp:
            protocols:
              http:
                endpoint: 0.0.0.0:4318
        remote_write:
          - endpoint: {{ .Values.observability.traces.endpoint }}
            basic_auth:
              username: {{ .Values.observability.traces.username }}
              password: {{ .Values.observability.traces.password }}
        batch:
          timeout: 5s
          send_batch_size: 100

