apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrent-config
data:
  config.yaml: |-
    fqdn: {{ .Values.concurrent.fqdn }}
    ccaddr: {{ .Values.concurrent.ccaddr }}
    publickey: {{ .Values.concurrent.publickey }}
    privatekey: {{ .Values.concurrent.privatekey }}
    dsn: {{ .Values.concurrent.dsn }}
    redisAddr: {{ .Values.concurrent.redisAddr }}
