apiVersion: v1
kind: Secret
metadata:
  name: hydra.acid-hydra-database.credentials.postgresql.acid.zalan.do
  labels:
    application: spilo
    team: acid
type: Opaque
stringData:
  username: {{ .Values.db.username }}
  password: {{ .Values.db.password }}
