
url: 'https://example.tld/'
port: 80

web:
  port: 3000
  fileStorageSize: '1Gi'
  image: 'misskey/misskey'
  NODE_ENV: 'production'

db:
  name: 'misskey'
  hostname: 'misskey-db'
  port: 5432
  postgresVersion: 15
  replicas: 1
  storageClassName: 'nfs'
  storageSize: '1Gi'
  username: 'misskey-user'
  password: 'misskey-pass'
  backup:
    bucket: '<YOUR_AWS_S3_BUCKET_NAME>'
    endpoint: '<YOUR_AWS_S3_ENDPOINT>'
    region: '<YOUR_AWS_S3_REGION>'
    accesskeyid: '<YOUR_AWS_S3_KEY>'
    secretaccesskey: '<YOUR_AWS_S3_KEY_SECRET>'
    schedules:
      full: "0 20 * * *"
      differential: "*/6 20 * * *"

redis:
  hostname: 'misskey-redis'
  port: 6379
  image: 'redis:7-alpine'

