
url: 'https://example.tld/'
port: 80

web:
  port: 3000
  fileStorageSize: '1Gi'
  image: 'misskey/misskey'
  NODE_ENV: 'production'
  replicas: 1

db:
  hostname: 'misskey-db'
  port: 5432
  name: 'misskey'
  username: 'misskey-user'
  password: 'misskey-pass'
  fileStorageSize: '1Gi'
  image: 'postgres:15-alpine'

redis:
  hostname: 'misskey-redis'
  port: 6379
  image: 'redis:7-alpine'

backup:
  enabled: true
  cron: '* 20 * * *'
  s3key: 's3://examplebucket/'
  aws_access_key_id: ''
  aws_secret_access_key: ''
  aws_default_region: 'ap-northeast-1'

