
server:
  dsn: "host=db user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

concurrent:
  fqdn: example.tld
  registration: invite
  ccid: CCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  publickey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

activitypub:
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  notificationstream: xxxxxxxxxxxxxxxxxxxx@example.tld

ccgateway:
  image: ghcr.io/totegamma/ccgateway:master

ccapi:
  image: ghcr.io/totegamma/ccapi:master

ccactivitypub:
  image: ghcr.io/totegamma/ccworld-ap-bridge:latest

ccwebui:
  image: ghcr.io/totegamma/ccwebui:master

url-summary:
  enabled: true
  LB_LISTEN_PORT: 80
  APP_TARGET_PORT: 8080
  CORS: ""
  LB_TYPE: ClusterIP

observability:
  metrics:
    endpoint: ""
    password: ""
    username: ""
  logs:
    url: ""
  traces:
    endpoint: ""
    password: ""
    username: ""

profile:
  nickname: concurrent-domain
  description: domain description
  logo: ''
  wordmark: ''
  themeColor: "#20193b"
  rules: |
    - リスペクトを持って接しましょう
      Treat everyone with respect
    - スパムは禁止です
      No spamming
    - 攻撃的なプロフィール名・画像はやめましょう
      No offensive names and profile pictures
  tosURL: ''
  maintainerName: changeme
  maintainerEmail: changeme@example.com

