apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmos-seed
spec:
  rules:
    # lcd
    - host: {{ .Values.ingress.lcd_endpoint }}
      http:
        paths:
          - backend:
              service:
                name: cosmos-seed
                port:
                  number: 1317
            path: /
            pathType: Prefix

    # rpc
    - host: {{ .Values.ingress.rpc_endpoint }}
      http:
        paths:
          - backend:
              service:
                name: cosmos-seed
                port:
                  number: 26657
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.lcd_endpoint }}
        - {{ .Values.ingress.rpc_endpoint }}
      secretName: cosmos-seed-ingress-cert

